# version: '3.4'

services:
  todoapp:
    container_name: todoapp
    command: python manage.py runserver 0.0.0.0:8080
    image: todoapp
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SECRETKEY=test
      - DEBUG=True
    ports:
      - 8000:8000
