# Generated by Django 5.1.1 on 2025-01-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plane',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
